accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'              # accountapp 이름을 적어주어 다른 파일에서 라우팅해줄 수 있는 것.

# name 인자를 기반으로 다른 파일에서 라우팅해줄 수 있는 것.
urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'), # create는 없는 것을 만드는 것
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'), # 다만 detail은 주소<int:pk>를 넘겨받아야!
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'), # 정보 수정이므로 user 키값 받아야.
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'), # 회원 정보 삭제이므로 마찬가지로 pk 값 받아야
]

gis_4ban_1/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'     # 이렇게 app_name 설정해주어야 나중에 'profileapp:create' 와 같은 방식으로 정해줄 수 있음!!

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.

class NewModel(models.Model): # models 패키지 안에 있는 Model을 상속받겠다
    text = models.CharField(max_length=255, null=False) # 캐릭터 필드를 통해 문자열을 받을 것이다(최대 255자, null 허용 안함)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    # onetoonekey는 1대1이였다면, foreignkey는 1대다
    # cascade(종속)가 user가 삭제되면 article 또한 삭제였다면, set_null은 user가 없어져도 신원 미상으로는 article 존재.
    writer = models.ForeignKey(User, on_delete=models.SET_NULL,
                               related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL,
                                related_name='article', null=True, blank=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=True)    # media 안에 article이라는 파일이 생기고 그 안에 이미지가 저장.
    content = models.TextField(null=True)    # 장문을 쓸 경우에는 textfield
    created_at = models.DateField(auto_now_add=True)    # DB에 저장되는 순간의 시각을 알아서 찍어줌

    like = models.IntegerField(default=0)   # 게시글 처음 생성 시 좋아요는 0개

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm): # auth\forms.py의 UserCreationForm 상속
    # override, super method
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # username이라는 이름의 필드를 찾고, disabled 속성 True로.
        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountCreationForm
from accountapp.models import NewModel
from articleapp.models import Article


class AccountCreateView(CreateView): # 장고의 뷰의 제너릭에서 CreateView import
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('articleapp:list') # 함수가 아니라 클래스에서 사용하기 때문에 reverse_lazy 사용
    template_name = 'accountapp/create.html' # 곧 만들 subscribe.html

    # def get_success_url(self):
    #     return reverse('accountapp:detail', self.object.pk) # accountapp이므로 바로 object.pk

class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User # User 객체의 detail을 보는 것이기 때문에
    context_object_name = 'target_user'         # key
    template_name = 'accountapp/detail.html'    # 추후에 만들 detail.html
    paginate_by = 20
    def get_context_data(self, **kwargs):
        article_list = Article.objects.filter(writer=self.object)
        return super().get_context_data(object_list=article_list, **kwargs)


has_ownership = [login_required, account_ownership_required]

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView): # 내 정보 수정
    model = User
    form_class = AccountCreationForm
    context_object_name = 'target_user'
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk}) # accountapp이므로 바로 object.pk

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView): # 삭제이므로 form_class 없어도 된다.
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{# bootstrap4 라이브러리 가져오기 - form 바꾸기 위해 #}
{% load bootstrap4 %}

{# content라는 이름으로 base.html에서 block을 설정해주었었다. #}
{% block content %}
    {# bootstrap에서 제공하는 text-center 속성 + max-width + bootstrap 좌우 마진 동일 #}
    <div class="text-center mw-500 m-auto">
        {#  상하좌우 마진 5만큼  #}
        <div class="m-5">
            <h4>Sign Up</h4>
        </div>
        <div>
            {#  url을 이용하여 reverse 방식과 같은 방식으로  #}
            <form action="{% url 'accountapp:create' %}" method="post">
                {% csrf_token %}
                {#  UserCreationForm에서 데려온 form 그대로 출력  #}
                {% bootstrap_form form %}
                {#  px-5 : x축 방향에 패딩 챙겨주는 속성  #}
                <div class="m-5">
                    <input type="submit" class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Quit</h4>
        </div>
        <div>
            {#  삭제한다는 데이터 정보도 보내는 것이므로 form 태그 지우면 안된다 #}
            <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                <div class="m-5">
                    <input type="submit"
                           value="Quit"
                           class="btn btn-danger rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="text-center mx-500 m-auto">
        <div class="m-5">
            {#  유저의 프로필이 있다면~  #}
            {% if target_user.profile %}
            {#  views.py에 정의해줬던 target_user 속성 사용  #}
                <img src="{{ target_user.profile.image.url }}"
                     class="profile_image m-4"
                     alt="profile image">
                <h2 class="NNS_B">
                    {{ target_user.profile.nickname }}
                    {% if target_user == user %}
                        {#  accountapp의 target_user의 profile의 pk 값!!  헷갈리지말자 #}
                        <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                        class="material-icons round_button">edit</a>
                    {% endif %}
                </h2>
                <h5>{{ target_user.profile.message }}</h5>
            {% else %}
            <h2>
                <a href="{% url 'profileapp:create' %}">
                    Create Profile
                </a>
            </h2>
            {% endif %}
        </div>
        {#  user와 target_user(서버에서 빼낸 Account 객체)가 같다면 회원정보 수정, 탈퇴 버튼 보이게끔  #}
        {% if user == target_user %}
        <div>
            <a href="{% url 'accountapp:update' pk=target_user.pk %}"
            class="material-icons round_button mx-1">settings</a>
            <a href="{% url 'accountapp:delete' pk=target_user.pk %}"
            class="material-icons round_button mx-1">close</a>
        </div>
        {% endif %}
    </div>

    <div>
        {% include 'snippets/list_fragment.html' with article_list=object_list %}
    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{# content라는 이름으로 base.html에서 block을 설정해주었었다. #}
{% block content %}
    {# bootstrap에서 제공하는 text-center 속성 #}
    <div class="text-center mw-500 m-auto">
        {#  상하좌우 마진 5만큼  #}
        <div class="m-5">
            <h4>Login</h4>
        </div>
        <div>
            {#  url을 이용하여 reverse 방식과 같은 방식으로  #}
            <form action="{% url 'accountapp:login' %}" method="post">
                {% csrf_token %}
                {#  UserCreationForm에서 데려온 form 그대로 출력  #}
                {% bootstrap_form form %}
                {#  px-5 : x축 방향에 패딩 챙겨주는 속성  #}
                <div class="m-5">
                    <input type="submit" class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Update Info</h4>
        </div>
        <div>
            {#  action : 어떤 주소로 데이터를 보낼지! / target_user의 pk 값을 입력  #}
            <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                    <input type="submit" class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>
{% endblock %}