articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name='articleapp'   # articleapp의 templates에 접근하기 위해 설정해줌

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),

]

gis_4ban_1/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    # onetoonekey는 1대1이였다면, foreignkey는 1대다
    # cascade(종속)가 user가 삭제되면 article 또한 삭제였다면, set_null은 user가 없어져도 신원 미상으로는 article 존재.
    writer = models.ForeignKey(User, on_delete=models.SET_NULL,
                               related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL,
                                related_name='article', null=True, blank=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=True)    # media 안에 article이라는 파일이 생기고 그 안에 이미지가 저장.
    content = models.TextField(null=True)    # 장문을 쓸 경우에는 textfield
    created_at = models.DateField(auto_now_add=True)    # DB에 저장되는 순간의 시각을 알아서 찍어줌

    like = models.IntegerField(default=0)   # 게시글 처음 생성 시 좋아요는 0개

templates/snippets/list_fragment.html
{# article grid 가져오기 #}

{% load static %}
    <style>
        .container {
            padding: 0;
            margin: 0 auto;
        }
        .container div {
          width: 45%;
            max-width: 200px;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          border-radius: 0.5rem;
          {#box-shadow: 0 0 0.2rem grey;#}
        }
        .container img {
            width: 100%;
            border-radius: 0.5rem;
        }
    </style>

    <div class="container my-4">

        {% for article in article_list %}
            <div>
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    <img src="{{ article.image.url }}" alt="">
                </a>
                <span class="my-2 NNS_B">{{ article.title }}</span>
            </div>

        {% endfor %}

    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script>

    {# snippets : 코드 조각을 의미  #}
    {% include 'snippets/pagination.html' %}

    <div class="text-center my-5">
        <a href="{% url 'articleapp:create' %}" class="btn btn-dark rounded-pill material-icons">
            brush
        </a>
        <a href="{% url 'articleapp:create' %}" class="btn btn-outline-dark rounded-pill px-5">
            Create Article
        </a>
    </div>

templates/snippets/pagination.html
{#  Pagination  #}
<div class="text-center my-5">
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="btn rounded-pill">
            {{ page_obj.previous_page_number }}
        </a>
    {% endif %}
    <a href="#" class="btn btn-light rounded-pill">
        {{ page_obj.number }}
    </a>
    {% if page_obj.has_next %}
        {# ? : get 방식으로 데이터 넘기기 #}
        <a href="?page={{ page_obj.next_page_number }}" class="btn rounded-pill">
            {{ page_obj.next_page_number }}
        </a>
    {% endif %}
</div>