accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'              # accountapp 이름을 적어주어 다른 파일에서 라우팅해줄 수 있는 것.

# name 인자를 기반으로 다른 파일에서 라우팅해줄 수 있는 것.
urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'), # create는 없는 것을 만드는 것
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'), # 다만 detail은 주소<int:pk>를 넘겨받아야!
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'), # 정보 수정이므로 user 키값 받아야.
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'), # 회원 정보 삭제이므로 마찬가지로 pk 값 받아야
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name='articleapp'   # articleapp의 templates에 접근하기 위해 설정해줌

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),

]

gis_4ban_1/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/<int:project_pk>', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR'">

{% include 'header.html' %}
<hr>

{% for message in messages %}
    <div class="text-center">
        {#  message tag를 커스터마이즈  #}
        <div class="btn btn-{{ message.tags }} rounded-pill px-5">
            {{ message }}
        </div>
    </div>
{% endfor %}

{% block content %}
{% endblock %}

<hr>
{% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div style="text-align: center;" >

    <div class="pragmatic_footer_button">
        <span>2021</span>
        <span>03</span>
        <span>08</span>
    </div>
    <div class="pragmatic_footer_logo">
        <h5>2022년의 우리 coming soon</h5>
    </div>

</div>

templates/head.html
{% load static %}
{# static(=내부자산) 구문을 가져오겠다~ #}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>2021년의 우리</title>

    {#  Bootstrap link  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    {#  Google Fonts link : pacifico 폰트, 고운바탕 폰트 #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Gowun+Batang&display=swap" rel="stylesheet">

    {#  default css link  #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {#  Material Icons Link  #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">


    {# static - fonts #}
    {#  src : local 컴퓨터에서 나눔스퀘어 폰트를 찾고, 만약 없다면, url : 우리 서버 요청해서 폰트 받아가~  #}
    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div style="text-align: center;">
    <div class="pragmatic_header_logo">
        <h1><a href="{% url 'home' %}">2021년의 우리</a></h1>
    </div>
    <div class="pragmatic_header_button">
        <span class="mx-2">
            <a href="{% url 'articleapp:list' %}">스토리</a>
        </span>
        <span class="mx-2">
            <a href="{% url 'projectapp:list' %}">출연</a>
        </span>

        {% if user.is_authenticated %}
        <span class="mx-2">
            <a href="{% url 'subscribeapp:list' %}">구독</a>
        </span>
        {% endif %}

        {#  로그인 되어있지 않다면  #}
        {% if not user.is_authenticated %}
        <span class="mx-2">
            <a href="{% url 'accountapp:login' %}">로그인</a>
        </span>
        <span class="mx-2">
            <a href="{% url 'accountapp:create' %}">회원가입</a>
        </span>
        {#  로그인 되어있는 상태라면  #}
        {% else %}
        <span class="mx-2">
            {#  user의 pk를 추가해줘야!  #}
            <a href="{% url 'accountapp:detail' pk=user.pk %}">내 소개</a>
        </span>
        <span class="mx-2">
            <a href="{% url 'accountapp:logout' %}">로그아웃</a>
        </span>
        {% endif %}
    </div>
</div>